### ISSUE TITLE
runing cmd 'protoc' in the bash script will miss some files

### ISSUE THREAD

**Issue by ape-casear** [stephenh/ts-proto#1076] opened 2024-07-17 06:17 UTC
first of all, my cmd is 
`protoc --plugin=./node_modules/ts-proto/protoc-gen-ts_proto  --ts_proto_opt=forceLong=string --ts_proto_opt=onlyTypes=true  --ts_proto_opt=snakeToCamel=false   --ts_proto_out=./out-ts -I=${APP_DIR}  ${APP_DIR}/**/*.proto`

when I run this cmd on the terminal, everything is ok.

but, when I run this cmd in the bash script just like:
```bash
#! /bin/sh

protoc --plugin=./node_modules/ts-proto/protoc-gen-ts_proto  --ts_proto_opt=forceLong=string --ts_proto_opt=onlyTypes=true  --ts_proto_opt=snakeToCamel=false   --ts_proto_out=./out-ts -I=${APP_DIR}  ${APP_DIR}/**/*.proto
```

the output only contains 79 files while the  expectation is 241 files

this has been bothering me for a while, I want to know why

my device is: macbook pro  m1pro

**Comment by ape-casear** [comment] 2024-07-17 08:37
now my hack solution is dividing the task into two steps. 
step1 processing all proto files in the level 1;
step2 processing all proto files in the level 2;

**Comment by stephenh** [comment] 2024-07-17 12:53
It sounds like you need to use `/bin/bash` instead of `/bin/sh`. You might also have to enable `shopt -s globstar`.

Hopefully that works, but otherwise I'm going to close this out because the issue isn't a bug in ts-proto itself. Thanks!

**Closed by stephenh** 2024-07-17 12:53 UTC
