### ISSUE TITLE
Protoc throwing "basic_string::_M_construct null not valid" when trying to generate types

### ISSUE THREAD

**Issue by pietruszka123** [stephenh/ts-proto#1095] opened 2024-08-20 15:23 UTC
When running: `protoc --plugin=node_modules/ts-proto/protoc-gen-ts_proto .\proto\sdp.proto -I. --ts_proto_out=.` on
```protobuf
//sdp.proto
syntax = "proto3";

message sdp{
    int32 protocolVersion = 1; //v=
    Originator originator = 2; //o=
    repeated string sessionAtributes = 3; //a=
    string mediaName = 4; // m=
    NetworkAddress connectionInformation = 5; //c=
    repeated string mediaAtributes = 6; //a=
}
message Originator{
    int64 id = 1;
    int64 versionNumber = 2;
    NetworkAddress networkAdress = 3;
}
enum IpType{
    ipv4 = 0;
    ipv6 = 1;
}
message NetworkAddress{
    string ip = 1;
    IpType ipType = 2;
}
```
protoc returned 
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
```

```json
//tsconfig.json
{
  "extends": "@tsconfig/svelte/tsconfig.json",
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "resolveJsonModule": true,
    /**
     * Typecheck JS in `.svelte` and `.js` files by default.
     * Disable checkJs if you'd like to use dynamic types in JS.
     * Note that setting allowJs false does not prevent the use
     * of JS in `.svelte` files.
     */
    "allowJs": true,
    "checkJs": true,
    "isolatedModules": true,
    "moduleDetection": "force"
  },
  "include": ["src/**/*.ts", "src/**/*.js", "src/**/*.svelte"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
```
```json
//tsconfig.node.json
{
  "compilerOptions": {
    "composite": true,
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.node.tsbuildinfo",
    "skipLibCheck": true,
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "noEmit": true
  },
  "include": ["vite.config.ts"]
}
```
```json
//node_modules/@tsconfig/svelte/tsconfig.json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "_version": "5.0.0",

  "compilerOptions": {
    "module": "esnext",
    "moduleResolution": "bundler",
    "target": "es2017",
    /**
      Svelte Preprocess cannot figure out whether you have a value or a type, so tell TypeScript
      to enforce using `import type` instead of `import` for Types.
     */
    "verbatimModuleSyntax": true,
    /**
      To have warnings/errors of the Svelte compiler at the correct position,
      enable source maps by default.
     */
    "sourceMap": true,

    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true
  }
}
```

**Comment by stephenh** [comment] 2024-08-21 13:37
Hi @pietruszka123 ! I believe this is an error in `protoc` itself, and not `ts-proto`; i.e. see this issue in the grpc repo:

https://github.com/grpc/grpc/issues/19601

The `basic_string` is coming from the `protoc` C++ and not anything in ts-protos JS code...

The ^ issue mentions maybe changing locale/environment settings?

Dunno, I'd love to hear what fixes this for you, if you find the root cause, but otherwise I'm going to close the issue b/c it's not something that I think we can fix/control from within ts-proto. Thank you, and good luck!

**Closed by stephenh** 2024-08-21 13:37 UTC
