### ISSUE TITLE
Repeated fields can be undefined

### ISSUE THREAD

**Issue by dot-i** [stephenh/ts-proto#225] opened 2021-02-27 12:57 UTC
It appears that a repeated field like this one:

```
   repeated Document documents = 2;
```

Simply gives this as output:

```
   documents: Document[];
```

But, if you use the standard NodeJS `protobufjs` serialization *without* adding `defaults: true` a deserialized message won't actually contain a `documents` field.

So it seems more appropriate to output:

```
   documents: Document[] | undefined;
```

Or even:

```
   documents?: Document[];
```

Of course, it's always possible to add an option to turn this on or off using a setting similar to `--ts_proto_opt=stringEnums=true` (which BTW does nicely fit the the `enums: String` override on the `protobufjs` (de)serializer).

I could help on a PR for this, but first wanted to check what the preferred solution could be.

**Comment by stephenh** [comment] 2021-02-27 15:37
The proto3 spec is pretty clear that, when deserializing repeated fields, the initial value is always an empty list:

"The default value for repeated fields is empty (generally an empty list in the appropriate language)."

https://developers.google.com/protocol-buffers/docs/proto3

I get that doesn't match what you personally are looking for, but that's why it is that way today.

Right now the `useOptionals` flag changes message keys from `foo: SomeMessage | undefined` to `foo?: SomeMessage`, so we could potentially extend that existing flag to let repeated field keys be optional. Note that this flag doesn't change any deserialization behavior, it just changes the types.

IIRC your use case is "take some JSON off the wire and just use it after `JSON.parse` w/o `Message.fromJSON`" ... that's fine, but that's not how proto3 JSON serialization is spec'd to work, which is why you're running into these problems. I'm fine with ts-proto supporting this use case, but it probably needs to be thought about wholistically and maybe even have its own dedicated flag.

...like... `matchJsonOnTheWire=true` or some better than like that.

A baby step PR to make repeated fields optional with the existing `useOptional` flag seems like a good baby step.

**Comment by dot-i** [comment] 2021-03-01 09:18
I liked your last suggestion and went for the baby step PR already: https://github.com/stephenh/ts-proto/pull/227

**Comment by stephenh** [comment] 2021-03-03 01:55
Should be released as v1.70.0, thanks!

**Comment by mharsat** [comment] 2021-03-07 08:55
Hey @stephenh, this change breaks current usage and introduces an unexpected behavior that doesn't comply with the [proto3 defaults guide](https://developers.google.com/protocol-buffers/docs/proto3#default)

Repeated fields should always default to an empty array, not to `undefined`. The introduced change both creates an unexpected behavior and misrepresents the type returned from the `fromJson` methods.
The reason is that the `fromJson` method initializes `message.repeatedFieldName = [];` **but the returned type is suddenly optional**.

I suggest reverting this change and introducing a new change with the following behavior:

1. `useOptionals` only changes `field: Type | undefined` to `field?: Type`.
2. A new non-breaking option is introduced for allowing the custom behavior (`forceOptionalRepeated`?).

```proto
Message Type1 {
	repeated Type2 field1 = 1;
	Type2 field2 = 2;
}
```

With `useOptionals=false` and `forceOptionalRepeated=false`

```ts
export interface Type1 {
  field1: Type2[];
  field2: Type2 | undefined;
}
```

With `useOptionals=false` and `forceOptionalRepeated=true`

```ts
export interface Type1 {
  field1: Type2[] | undefined;
  field2: Type2 | undefined;
}
```

With `useOptionals=true` and `forceOptionalRepeated=true`

```ts
export interface Type1 {
  field1?: Type2[];
  field2?: Type2;
}
```

With `useOptionals=true` and `forceOptionalRepeated=false`

```ts
export interface Type1 {
  field1: Type2[];
  field2?: Type2;
}
```

**Comment by stephenh** [comment] 2021-03-07 17:15
Hey @mharsat , thanks for the report! I was worried about this, per discussion above, i.e. you're right, this is "not proto3" behavior.

I was hoping that existing users of `useOptional` would be fine with this, but I guess you're right that `useOptionals` as it was before this PR was only a type-system change and not a decoding behavior change, which is what this PR turned it into...

I'll revert and push out a new version.

I like your description of `forceOptionalRepeated` ... I kinda wonder if something like `dontApplyDefaults` or even `matchJsonOffTheWire` would be more higher-level/use-case-driven names given that afaiu that is what @dot-i is looking to achieve.

**Comment by stephenh** [comment] 2021-03-08 14:53
Okay, I pushed v1.72.0 that reverts the change, and we can work on a redo.

**Comment by dot-i** [comment] 2021-03-09 18:44
Message received and understood, I'll pick it up... 🙂

**Comment by dot-i** [comment] 2021-03-10 08:56
I implemented the `forceOptionalRepeated=true` flag, added two more tests and a short description to the readme.

https://github.com/stephenh/ts-proto/pull/234

**Comment by medikoo** [comment] 2022-12-07 14:57
The current way of handling _repeated_ doesn't feel right.

Adding a new _repeated_ field to the schema, shouldn't require updates to the application code, as per Protobuf spec _repeated_ fields are optional (if not provided, they resolve to an empty list).

While with current `ts-proto` implementation, adding a new _repeated_ field makes a breaking change.
As all applications which depend on the schema and create complying objects will crash until we ensure that array values for introduced properties are added. That shouldn't be the case.

Ideally, there should be at least an option to relax that, so _repeated_ fields are not implemented as _required_

**Comment by medikoo** [comment] 2022-12-08 11:37
@stephenh yes, it relaxes this restriction, but it also relaxes restriction on primitive values which are not marked as _optional_. So it introduces another issue

**Comment by stephenh** [comment] 2022-12-15 02:19
@medikoo hm, it sounds like you want "repeated fields per spec are optional" (so adding new repeated fields doesn't require updating app code), but you do want "non-optional primitive fields are required" (so adding new primitive fields _does_ require updating app code), even though "primitive fields per proto3 spec are also optional / have default values".

If I'm following, this seems inconsistent? 

Fwiw I think this issue was originally file before we had `useOptionals=all`, so I'm going to close it out for now. Happy to re-open/file a follow up issue if there's a good articulation for a new `useOptionals=<...>` flag, but in general optional-vs-required is generally a mess in proto3 and it ends up being very hard to please everyone. :-)

**Closed by stephenh** 2022-12-15 02:19 UTC

**Comment by medikoo** [comment] 2022-12-15 09:15
@stephenh I believe the correct understanding of spec is as follows:

```protobuf
message Test {
  // required primitive property
  string lorem = 1; 

  // optional primitive property
  optional string ipsum = 2;

  // optional repeated primitive property (note that spec does not support "optional repeated" notation)
  repeated string other = 3
}
```

And while `ts-proto` differenties between _required_ and _optional_ primitives (without any extra flags), it assumes _repeated_ as _required_ which I believe is not correct

**Comment by stephenh** [comment] 2022-12-16 15:11
@medikoo the default ts-proto output is focused on _reading_ values and not writing them.

From the [Default values](https://developers.google.com/protocol-buffers/docs/proto3) section:

* For strings, the default value is the empty string.
* ...
* The default value for repeated fields is empty

So if a reader does `Test.decode(...)`, they cannot tell "did the writer have test.other = not set or did they have test.other = []". The spec says the reader should, for either of these cases, see `other = []` as the default value.

Granted, a wrinkle of ts-proto's "just POJO interfaces" approach is that we use the same types for readers vs. writers, and you're focused on "when _writing_ / _creating_"; for that we have the `fromPartial` methods, which will let you leave out `other` on create, and let `fromPartial` apply the `test.other = []` to match the spec-recommended defaults.

If you're unhappy with using `fromPartial`, that is what the `useOptionals=all` is for, to make the POJO types look more like "what writers care about" instead of "what readers care about".

**Comment by medikoo** [comment] 2022-12-16 16:16
> @medikoo the default ts-proto output is focused on reading values and not writing them.

Yes, and the current situation is that it (1) ignores if _optional primitive_ is not provided, (2) crashes if _required_ primitive is not provided, and (3) (!) crashes if _optional_ repeated primitive is not provided.

If for above schema, I'll do `Test.encode({ lorem: "whatever" })`, it'll accept fact that `ipsum` was not provided, yet it'll crash on missing `other`. This is the problem I'm referring to

**Comment by stephenh** [comment] 2022-12-16 16:28
@medikoo do you mean "crashes" as in "throws a runtime error" or "crashes" as in it's a typescript compile error? 

If you mean "typescript compile error", yes, that behavior is still expected because:

1) for readers, the wire protocol can different "`ipsum` is set" vs. "`ipsum` is not set"
2) for readers, the wire protocol _cannot_ differentiate "`other` is set" vs. "`other` is not et"

I.e. you're confusing "what is the best API for readers" (what the `Test` interface, by default, is optimized for) with "what is the best API for _creating a new message_".

I.e. ts-proto does not leave `ipsum` out of `Test.encode({ lorem: "whatever" })` because it's "optional on create", it leaves it out because "the reader can actually differentiate ipsum-is-set vs. ipsum-is-not-set".

With the default ts-proto output, you should use `Test.encode(Test.fromPartial({ lorem: "whatever" }))`. Or set `useOptionals=all`.

**Comment by medikoo** [comment] 2022-12-16 16:33
> @medikoo do you mean "crashes" as in "throws a runtime error" 

I was referring to JavaScript execution of TS compiled to JS.

I do not see any reasonable explanation for being ok not to pass optional primitive, but not being ok to not pass optional repeated primitive.

**Comment by JeHwanYoo** [comment] 2024-01-18 00:13
What happened to this issue in the end?

Let me show you my case.

```ts
// from grpc server

@GrpcMethod('UsersService')
  findAll(request: GrpcUser.UserQuery): Observable<GrpcUser.UserPage> {
    return from(this.userEntity.find()).pipe(
      switchMap(users => {
        console.log('GrpcMethod', users) // users are '[]'

        return of({
          users,
        })
      }),
    )
  }
  ```
 
 ```ts
 // from grpc client
   findAll() {
    return this.usersGrpcService.findAll({}).pipe(
      switchMap(({ users }) => {
        console.log('GraphQL', users) // users are 'undefined' !????

        return of(users ?? [])
      }),
    )
  }
 ```
 
 ```ts
 // compiled ts file
 
 export interface UserPage {
  users: User[]; // The return value cannot be undefined.
}
 ```
 
 ```bash
 # ts-proto option
 TS_ARGS_SERVER=('lowerCaseServiceMethods=true'
  'outputEncodeMethods=false'
  'outputJsonMethods=false'
  'outputClientImpl=false'
  'snakeToCamel=true'
  'returnObservable=true'
  'useDate=true'
  'env=node')
 ```

**Comment by biljecki** [comment] 2024-03-15 00:57
@JeHwanYoo any luck here? im also getting undefined for empty arrays in client, dont get what the point of that is
