### ISSUE TITLE
Supporting NestJS with observables and also metadata, pull request added.

### ISSUE THREAD

**Issue by iangregsondev** [stephenh/ts-proto#44] opened 2020-04-03 20:32 UTC
Hi,

I while ago I started a thread with regards to returning only the interface for the generated code. Due to lack of time I wasn't able to complete it but somebody else provided the functionality.

I have now further extended it as "opt in" to return an observable in place of a promise and also accept a Metadata parameter.

This is really helpful for the NestJS community which I am part of.

https://github.com/stephenh/ts-proto/pull/47

If anybody cares to comment, I am open to suggestions.

It doesn't break compatibility and as mentioned, is OPT-IN only.

I have updated the readme.

Thanks in advance.

**Comment by tlinford** [comment] 2020-04-23 09:53
Stumbled upon this while looking for ways to not have to generate interfaces by hand for a grpc client in Nest JS.
Would be very useful, have tested the branch it seems to work fine.
@stephenh any plans to include this?

**Comment by iangregsondev** [comment] 2020-04-23 11:05
Hi @tlinford , I had a few false starts with this .. But it does work now.

I am not sure about the API choices I made.

I would love to get it merged only so I have less maintenance :-) AH AH.

Please feel free to comment on the pull request to see if it can be improved.

If @stephenh doesn't decide to include it then I can move it into its own repo - but I would love to see it merged.

**Comment by stephenh** [comment] 2020-04-23 12:54
Yeah, I'm good this including this; I thought I'd asked some clarifying questions somewhere, but I don't see them now.

@iangregsondev are you generating interfaces for the NestJS client-side or server-side? Because those are different things in NestJS?

Specifically I'm thinking of the `metadata` param you're adding; that looks like it's from implementing a server-side `HelloController`:

```typescript
@Controller()
export class HeroService {
  @GrpcMethod()
  findOne(data: HeroById, metadata: any): Hero {
    const items = [
      { id: 1, name: 'John' },
      { id: 2, name: 'Doe' },
    ];
    return items.find(({ id }) => id === data.id);
  }
}
```

But it's not included in interfaces used by the client:

```typescript
interface HeroService {
  findOne(data: { id: number }): Observable<any>;
}
```

So, will NestJS users want to generate potentially separate `HeroService` interfaces based on whether they're building a client (no `metadata` param) or implementing the controller (so yes `metadata` param)?

Fwiw I'd also like to see an `integration/nestjs` example added that uses these options with a sample proto file (i.e. the one from [the docs](https://docs.nestjs.com/microservices/grpc)) that shows a) what the generated code looks like with these new options and b) how the NestJS client or server whatever you're doing would use the interface. These would essentially be regression tests to ensure your approach doesn't break.

If you want to add nestjs as a dev dependency to the ts-proto package.json to test this scenario, I think that'd be fine. Maybe eventually each `integration/foo` test could have its own package.json for framework-specific dependencies like this, but it seems fine for now to put nestjs as a top-level dev depenency.

**Comment by iangregsondev** [comment] 2020-04-23 14:25
Hi @stephenh , yep about the previous questions, that was my bad - i did answer them but it was on a previous pull request that some BOT closed  - my fault on my end.

Anyway, let me answer them here.

1. The interface can be used on both the client and the server. They are actually exactly the same - the only difference is the decorators.

The meta-data is used to received information from the client, it's valid on both client and server. I have actually marked it as optional in the interface anyway. It really is great for passing down a JWT for example :-) 

The nestjs user wouldn't create a different interface depending on if its a client or. a server. With regards to the metadata. if they don't want to pass anything down - then they don't need to use it. It's all optional if used anyway.

As I say for me the use case is passing down a JWT. If I wasn't doing thing I don't think I would need the metadata.

I can add some docs, no probs.

Unit tests, ok not sure how I would test this as its an interface - but let me have a look at it.

I will try and looks little later today and start updating the pull requests.

I promise i disabled any stupid bot my end - so we won't get anything automatically closed.

If you like we can continue the conversation over at the pull request - when I commit some new things.

**Comment by stephenh** [comment] 2020-04-23 14:33
> not sure how I would test this as its an interface

Fwiw the "test" could just be "the `hero.ts` file is generated, and I have a `hero-client.ts` (or controller or whatever) that has a `class Foo implements HeroService` and it compiles".

I.e. right, don't actually need to "invoke" the client/server side of things to make actual wire calls, but just write some code that uses `hero.ts` and would not compile if the output is not correct.

**Comment by stephenh** [comment] 2020-04-23 14:35
Fwiw I'd also be open to some sort of `nestJs=true` option flag that set the 3 other flags of grpc metadata / output impl / etc. to the appropriate values. Just to shorten things up for NestJS users.

**Comment by iangregsondev** [comment] 2020-04-23 14:53
> > not sure how I would test this as its an interface
> 
> Fwiw the "test" could just be "the `hero.ts` file is generated, and I have a `hero-client.ts` (or controller or whatever) that has a `class Foo implements HeroService` and it compiles".

Ok - cool  - let have a look at that. I did have some issues running the existing tests BUT I have just merged the latest from base to my fork - let's see how I get on. Looking at it now.

**Comment by iangregsondev** [comment] 2020-04-23 14:53
> Fwiw I'd also be open to some sort of `nestJs=true` option flag that set the 3 other flags of grpc metadata / output impl / etc. to the appropriate values. Just to shorten things up for NestJS users.

Yep - totally agree. On it.

**Comment by iangregsondev** [comment] 2020-04-23 16:46
@stephenh I have started a number of conversations over at the actual pull requests. There are some issues with some existing tests.

https://github.com/stephenh/ts-proto/pull/47

**Comment by iangregsondev** [comment] 2020-04-23 17:56
@tlinford @stephenh Ok all done, please take a look at the pull request when you can.

Added tests also for all nestjs outcomes.

Updated the readme.

Fixed a small issue with tests not related to me, let me know if you are happy with the fix.

Awaiting comments :-) 

Cheers!

**Comment by iangregsondev** [comment] 2020-04-28 12:45
@stephenh Do you have any update for me?

**Comment by stephenh** [comment] 2020-04-29 13:28
@iangregsondev hey, sorry for lack of response, just been busy. Really appreciate your PR, I'll try to get it reviewed and merged this week. Definitely this weekend if not.

**Comment by iangregsondev** [comment] 2020-04-29 15:02
Ok thanks @stephenh , speak later.

**Comment by stephenh** [comment] 2020-05-03 16:25
Released in 1.19.0. Thanks!

**Closed by stephenh** 2020-05-03 16:25 UTC

**Comment by iangregsondev** [comment] 2020-05-03 16:37
Thanks @stephenh , this is great, I know the nestjs community needs and wants this - so maybe somebody else can come along and help even improve it further!

**Comment by stephenh** [comment] 2020-05-03 16:49
@iangregsondev nice, that'd be great to see wider adoption in the nestjs community. As you can tell, I'm not personally a nestjs user / day job is on a different stack, but would love to see ts-proto find a larger audience that could use it / improve it / benefit from it.

Any FYIs / community evangelicalism you could do in that regard would be great. :-)

**Comment by iangregsondev** [comment] 2020-05-03 16:54
Already on it :-)

I know it will get adopted - I have been waiting for something for months - and nothing, that's why I created the PR.

I will get the news out there!

Thanks for accepting the PR, let's set see if we get additional PRs in the future. I think I did the base and it kind of does what I need but its open for improving if somebody sees the need.

Cheers.

**Comment by iangregsondev** [comment] 2020-05-03 17:08
@stephenh Another thing that might help, I presume when you are publishing to NPM you use tags, maybe adding a tag with NestJS and also adding something to the description about the support of NestJS - as well as other support of course.

I think the main thing is getting the news out there, you can't imagine how many times I searched github and npmjs for something similar before deciding to create a PR - although I am glad I did, it was a nice feeling getting something accepted and published :-)

Thanks.

**Comment by stephenh** [comment] 2020-05-03 17:23
Ah sure, good idea. I've added some github topics to see if that helps discoverability.

I have actually been surprised at how many users seem to have stumbled upon ts-proto somehow, given how little promotion I've done of it.

> a nice feeling getting something accepted and published

:1st_place_medal: :-)
