### ISSUE TITLE
error TS2308 has already exported a member named 'protobufPackage'.

### ISSUE THREAD

**Issue by xmlking** [stephenh/ts-proto#180] opened 2021-01-04 00:58 UTC
getting an error when exporting generated TS files.... 

ERROR in /Developer/Work/SPA/yeti/libs/gen/nest/src/index.ts(2,1):
TS2308: Module 'libs/gen/nest/src/lib/yeti/account/v1/account' has already exported a member named 'protobufPackage'. Consider explicitly re-exporting to resolve the ambiguity.
ERROR in /Developer/Work/SPA/yeti/libs/gen/nest/src/index.ts(3,1):
TS2308: Module 'libs/gen/nest/src/lib/yeti/account/v1/account' has already exported a member named 'protobufPackage'. Consider explicitly re-exporting to resolve the ambiguity.
Version: typescript 4.1.3

![image](https://user-images.githubusercontent.com/627951/103493212-c51fa600-4de4-11eb-9e9b-d285a88598d2.png)

![image](https://user-images.githubusercontent.com/627951/103493175-8be73600-4de4-11eb-9dca-e9688ffd30fa.png)

**Comment by stephenh** [comment] 2021-01-10 15:08
Duplicate of #167.

**Closed by stephenh** 2021-01-10 15:08 UTC
