### ISSUE TITLE
const and interface export under same name

### ISSUE THREAD

**Issue by lexdevelop** [stephenh/ts-proto#881] opened 2023-07-14 12:52 UTC
I'm generating proto with following options
`protoc --plugin=/usr/local/lib/node_modules/ts-proto/protoc-gen-ts_proto \
    $(find ./proto -iname "*.proto") -I proto/ \
    --ts_proto_out=/output/nestjs \
    --ts_proto_opt=nestJs=true \
    --ts_proto_opt=addGrpcMetadata=false \
    --ts_proto_opt=addNestjsRestParameter=false \
    --ts_proto_opt=outputJsonMethods=true \
    --ts_proto_opt=outputEncodeMethods=true`
This will generate 
```
import * as _m0 from "protobufjs/minimal";

export const protobufPackage = "common.v1";

export interface Empty {
}

export const COMMON_V1_PACKAGE_NAME = "common.v1";

function createBaseEmpty(): Empty {
  return {};
}

export const Empty = {
  encode(_: Empty, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Empty {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Empty {
    return {};
  },

  toJSON(_: Empty): unknown {
    const obj: any = {};
    return obj;
  },
};
```

As we can see export interface Empty {} and export const Empty = {} which contins json and encode functions have same name, which will not allow me to import this module. Is there any solution for this, can i name interface with I prefix like export interface IEmpty{}

**Comment by lexdevelop** [comment] 2023-07-14 13:27
When i try to import I'm getting error like:
Error: Cannot find module 'astrabit-proto/proto/nestjs/pb/apex_exchange/v1/apex_exchange_service'

Removing  --ts_proto_opt=outputJsonMethods=true --ts_proto_opt=outputEncodeMethods=true will not compile const under same name and I don't have this issue.

Import looks like:
```
import {
  Empty,
} from 'astrabit-proto/proto/nestjs/pb/common/v1/common';
```

**Comment by stephenh** [comment] 2023-07-14 13:47
Hi @lexdevelop , the "cannot find module" error is not caused by the const+interface combination, but is just "this file cannot be found". My guess is that when you changed the opts, something else in your setup changed as well, and the file (module) can be found now.

Sorry I can't be more helpful, but the const+interface combination does work, for myself and many/all other ts-proto users, so I'm going to close this issue out.

**Closed by stephenh** 2023-07-14 13:47 UTC

**Comment by lexdevelop** [comment] 2023-07-14 15:10
You are right, in order to resolve this import needs to be done as following:
```
import {
  type Empty,
  Empty as EmptyTransformer,
} from 'xxxnamexxx/proto/nestjs/pb/common/v1/common';
```

So type Empty will be interface
EmptyTransformer is constant

This error "Error: Cannot find module" is related to wrong import because we have same name for different exported types

**Comment by achou11** [comment] 2023-09-07 15:11
just adding a +1 to say that this behavior is difficult to work with, especially in our use case where we're working with JSDoc + TS and not TS directly. Would be helpful to prefix the exported interfaces with `I` or provide some option to specify that prefix

**Comment by olejorgenb** [comment] 2025-03-26 14:27
I also found this quite confusing, but haven't experienced any actual issues yet.
