### ISSUE TITLE
issues with toJSON & fromJSON using nestJs=true & useDate=true

### ISSUE THREAD

**Issue by RealAdamSinger** [stephenh/ts-proto#451] opened 2021-12-21 14:16 UTC
I've tried every combination of the `useDate` option while sending an object with dates over grpc and it seems there is a bug with `useDate=true`.

When using `useDate=false`, `fromJSON` works as expected, converting the dates to seconds and nanos for transfer, after transfer, I use `toJSON` and I end up with ISO strings in their place. Makes sense.

But when using `useDate=true`, the generated `fromJSON` strangely returns JS date objects as JS date objects rather than nanos & seconds (or something else transferrable over grpc)... is this a bug or am I using these functions wrong? More documentation and some examples in the readme would go a long way. 

Thanks!

Expected Outcome: use generated `fromJSON` to convert date objects to something that could be transferred over GRPC, and then using `toJSON` on the other end to get my original date object back.

**Comment by stephenh** [comment] 2021-12-23 18:39
@RealAdamSinger I'm pretty sure this is a duplicate of #69, which is basically that for options like `useDate=true` (and other types were ts-proto makes "more ergonomic" versions than the stock protobuf messages), we've not yet figured out how to tell NestJS to use ts-proto's `encode` and `decode` methods.

I.e. ts-proto's `encode` method knows how to turn ts-proto's messages into a byte array, and it knows about the `Date` setting.

So we just need to tell NestJS about that, however I think we've been stymied by no one really digging into how / if this is configurable.

I.e. outside of NestJS, we have figured out how to tell the improbable-eng grpc-web library how to use ts-proto's `encode` / `decode` methods, and for raw grpc-js, it looks like there are hooks here: 

https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/make-client.ts#L156

For the `attrs.requestSerialize` and `attrs.responseDeserialize`, i.e. we'd set those to `FooMessage.encode` and `FooMessage.decode`.

If you can figure how the NestJS incantation to do this (like does NestJS sit on top of grpc-js? IANAE on NestJS so don't really know), we could probably adjust the codegen output to setup this wiring/configurable automatically, or at least cover it in the docs, that would be amazing.

I'm technically going to close this as a dup b/c I believe it is the same issue as #69 , but again it'd be great to have you dig in and figure this out. Thanks!

**Closed by stephenh** 2021-12-23 18:39 UTC
